# Generated by Django 4.2 on 2025-06-18 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authtoken', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise_type', models.CharField(choices=[('word_with_audio', 'Word with Audio'), ('image_selection', 'Image Selection'), ('pronunciation', 'Pronunciation'), ('matching', 'Matching Quiz')], max_length=20)),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('options', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('correct_answer', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('flag', models.CharField(default='🌐', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lesson_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('practice', 'Practice')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('xp_reward', models.PositiveIntegerField(default=10)),
                ('prerequisite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='myapp.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expires_at', models.DateTimeField()),
            ],
            bases=('authtoken.token',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.CharField(max_length=50)),
                ('daily_goal', models.PositiveIntegerField(default=5)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(default=django.utils.timezone.now)),
                ('last_streak_date', models.DateField(blank=True, null=True)),
                ('selected_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('title', models.CharField(help_text='Enter a title for this unit', max_length=200, verbose_name='Unit Title')),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines display order (lower numbers first)', verbose_name='Sort Order')),
                ('icon', models.CharField(default='📚', help_text='Icon to represent this unit', max_length=50, verbose_name='Display Icon')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='myapp.language', verbose_name='Associated Language')),
            ],
            options={
                'verbose_name': 'Learning Unit',
                'verbose_name_plural': 'Learning Units',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='myapp.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='myapp.unit'),
        ),
        migrations.AddIndex(
            model_name='language',
            index=models.Index(fields=['code'], name='myapp_langu_code_d91573_idx'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='myapp.lesson'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['language'], name='myapp_unit_languag_3d0587_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('language', 'title'), name='unique_unit_title_per_language'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('lesson', 'user')},
        ),
    ]
