# Generated by Django 4.2 on 2025-06-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_lessonprogress_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_goal_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gems',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hearts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='proficiency_level',
            field=models.CharField(default='beginner', max_length=50),
        ),
    ]
