# Generated by Django 4.2 on 2025-06-19 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_language_speech_recognition_code_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='myapp.language'),
        ),
    ]
