# Generated by Django 4.2 on 2025-06-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_unit_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='speech_recognition_code',
            field=models.CharField(default='en-US', help_text='Language code for speech recognition (e.g., fr-FR for French)', max_length=10),
        ),
    ]
