# Generated by Django 4.2 on 2025-07-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_notification_options_userprofile_daily_push_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
