# Generated by Django 4.2 on 2025-07-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userprofile_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weekly_summary',
            field=models.BooleanField(default=True),
        ),
    ]
