# Generated by Django 4.2 on 2025-07-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_userprofile_daily_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
