# Generated by Django 4.2 on 2025-07-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_userprofile_last_reminder_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_reminder_sent',
        ),
    ]
