# Generated by Django 4.2 on 2025-07-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_communitymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='myapp.communitymessage'),
        ),
    ]
